# Generated by Django 5.0.3 on 2024-03-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
